apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{},"labels":{"kubernetes.io/metadata.name":"unbound"},"name":"unbound"}}
  creationTimestamp: "2026-04-22T15:07:56Z"
  labels:
    kubernetes.io/metadata.name: unbound
  name: unbound
  resourceVersion: "46874"
  uid: 0ef07e5e-7667-42d4-92e0-e48e55beb3e9
spec:
  finalizers:
  - kubernetes
status:
  phase: Active