apiVersion: v1
data:
  unbound.conf: "server:\n  interface: 0.0.0.0\n  interface: ::0\n  port: 53\n  access-control:\
    \ 10.43.0.0/16 allow\n  access-control: 10.0.0.0/8 allow\n  access-control: 172.16.0.0/12\
    \ allow\n  access-control: 127.0.0.0/8 allow\n  access-control: ::1 allow\n  access-control:\
    \ fd00:7808:88c3:90::/64 allow\n  do-not-query-localhost: no\n  cache-max-ttl:\
    \ 86400\n  cache-min-ttl: 60\n  cache-max-negative-ttl: 3600\n  num-threads: 4\n\
    \  prefetch: yes\n  log-queries: no\n  log-replies: no\n  verbosity: 1\n"
kind: ConfigMap
metadata:
  name: unbound-config
  namespace: unbound
